References for ESEC/FSE21 and Before
SoftVarE-Group/BibTags pull request #40
Opened 2022-04-01 13:09 UTC by pmbittner

2022-04-04 16:08 UTC, SundermannC requested changes
Looks good. Only small changes required

2022-04-05 08:28 UTC, pmbittner commented on literature.bib
> +@inproceedings{SBG+:SE22,
good catch

2022-04-05 08:30 UTC, pmbittner commented on literature.bib
> +	keywords = {feature location, software product line, feature revision, repository mining, benchmark extractor},
These are the keywords from the ACM digital library (and thus likely specified by the authors). I can remove them but would not change them. This is a systematic problem in the publication mechanism that we cannot and should not fix with BibTags.

2022-04-05 08:33 UTC, pmbittner commented on literature.bib
> +	keywords = {feature location, software product line, feature revision, repository mining, benchmark extractor},
Do we have any policy for this? What should I use instead of `software product line`?

2022-04-05 08:36 UTC, pmbittner commented on literature.bib
> +	author = {Feichtinger, Kevin and St\"{o}bich, Johann and Romano, Dario and Rabiser, Rick},
added pages

2022-04-05 08:36 UTC, pmbittner commented on literature.bib
> +	title = {{How different are different diff algorithms in Git?}},
fixed

2022-04-05 08:40 UTC, SundermannC approved these changes

2022-04-05 08:50 UTC, SundermannC commented on literature.bib
> +	keywords = {feature location, software product line, feature revision, repository mining, benchmark extractor},
It seems like software product line**s** is used much more frequently than software product line in other entries. So I would argue for using software product line**s** as standard.

2022-04-06 11:19 UTC, merged